version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "80:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo-node-mongo-master
    image: mongo
    ports:
      - "27017:27017"
